name: Build Unsigned IPA

on:
  push:
    branches:
      - main  # Change this to your branch
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install Dependencies (if needed)
        run: |
          if [ -f "Podfile" ]; then
            brew install cocoapods
            pod install
          fi

      - name: Build and Archive Project
        run: |
          xcodebuild clean archive \
            -scheme YourSchemeName \  # Change this to your scheme
            -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO

      - name: Export Unsigned IPA
        run: |
          mkdir -p output
          xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/App.xcarchive \
            -exportPath output \
            -exportOptionsPlist exportOptions.plist \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload IPA as an Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned-IPA
          path: output/*.ipa
